### ISSUE TITLE
sbc keep create new regbot for same sip gateway

### ISSUE THREAD

**Issue by xquanluu** [jambonz/sbc-sip-sidecar#29]
sbc keep create new regbot for same sip gateway

**Comment by davehorton** [comment]
Can you provide more detail on what this bug is?

**Comment by xquanluu** [comment]
https://github.com/jambonz/sbc-sip-sidecar/blob/main/lib/sip-trunk-register.js#L237

Due to we have new column in sip gateway named register_status, this column is being updated by regbot for register status, that cause the comparison always true, and new Regbot object will be created every 1 minutes.

This action eat all memory after 4 hours and regbot cannot send REGISTER.

**Comment by davehorton** [comment]
ok thank you.
