### ISSUE TITLE
Need more flexibility in constructing Contact header in outgoing REGISTER

### ISSUE THREAD

**Issue by davehorton** [jambonz/sbc-sip-sidecar#3]
Currently, when sending REGISTERs to carriers that require it, we define the Contact header to have the address of record (aor) in the host part of the uri:

https://github.com/jambonz/sbc-sip-sidecar/blob/b6af3f12b1582e6f42a0ee4384546da5909aaf36/lib/sip-trunk-register.js#L52

However, some carriers (e.g. sipgate) require that the host part of the Contact header be the public address of the server sending the REGISTER.  Therefore, we need to add an environment variable which, if set, would cause the Contact header to be constructed using the local public IP of the drachtio server.

The env variable should perhaps be named JAMBONES_REGBOT_CONTACT_USE_IP and if set to '1' or true the code should construct the Contact header accordingly.  This will require learning the drachtio public ip in the callback from the 'connect' call and then storing it in srf.locals somwhere.

**Comment by xquanluu** [comment]
working on this now

**Comment by davehorton** [comment]
this was fixed in 0.7.7
