### ISSUE TITLE
Enable the use of two distinct usernames for outbound SIP REGISTER

### ISSUE THREAD

**Issue by javibookline** [jambonz/sbc-sip-sidecar#35]
Some PBX systems require additional SIP credentials for registration. One of these cases is where on top of the usual Domain/Username/Password triplet, the system uses a separate authentication username to be used in the authentication digest.

This means that for jambonz to register as an extension to that system, it would need to use the "standard" username in all SIP headers but when generating the Auth Digest, use the provided auth username instead.

Example:
-Username: 702
-Password: XXXXXX
-Auth Username: myauthuser

Should result in a request where all header fields use the Username (702) but the Digest is generated with the Auth Username (myauthuser)

<img width="938" alt="Captura de pantalla 2023-06-29 a las 11 39 17" src="https://github.com/jambonz/sbc-sip-sidecar/assets/98887695/02951922-f72e-41fa-85ba-d163810bf158">

Currently in Jambonz we can specify Username/Password for authenticating oubound calls - and that user/pass is used throughout all the fields in the SIP REGISTER request. The only additional field we can tweak at the moment (0.8.3) is the SIP From user.

![Captura de pantalla 2023-06-29 a las 11 45 27](https://github.com/jambonz/sbc-sip-sidecar/assets/98887695/c6a5a9bf-3d66-4d23-9573-ca3642f45e0f)

This only changes the SIP From header but the other fields still use the Username/Password specified in the authentication of outbound calls. The mix of usernames in the headers does not result in a successful registration.

<img width="939" alt="Captura de pantalla 2023-06-29 a las 11 47 41" src="https://github.com/jambonz/sbc-sip-sidecar/assets/98887695/1d222e97-ea5d-4ad7-9646-a282ca4ed4bb">

**Comment by davehorton** [comment]
Agree this makes sense.  I think we should also change the labels in the webapp as well to reflect this:
 - change "Username" to "Auth username"
 - change "SIP from user" to "Username (if different from auth username)"

**Comment by xquanluu** [comment]
Start working on this

**Comment by xquanluu** [comment]
closed as PRs merged
