### ISSUE TITLE
make process.env.JAMBONES_REGBOT_CONTACT_USE_IP a trunk setting instead of environment variable

### ISSUE THREAD

**Issue by Megamuch** [jambonz/sbc-sip-sidecar#5]
When registering and using the public IP of the jbz sbc as the AOR and getting that switch from ENV JAMBONES_REGBOT_CONTACT_USE_IP variable, I think it would be better to make this an individual trunk setting and not an ENV. 

 That way you can have the regbot use both scenario's.

**Comment by davehorton** [comment]
this was fixed in 0.7.7
